apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
  name: redis-master
  namespace: gic-chathub
spec:
  containers:
    - name: master
      image: registry.deti/gic-chathub/redis:latest
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
    - name: sentinel
      image: registry.deti/gic-chathub/redis:latest
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
  volumes:
    - name: data
      emptyDir: {}